### ISSUE TITLE
Tidy-up the CoAP example

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#276]
A couple of things to do here:

* [x] Remove discussion about the copper addon, which is no longer available
* [x] There is a patch file for wpacap / minimal-net. This needs removed
* [x] Do something about #273 

Perhaps more.

**Comment by simonduq** [comment]
Any update on this?

**Comment by simonduq** [comment]
Closed by https://github.com/contiki-ng/contiki-ng/pull/434
